name: Dispatch and Destroy

on:
  repository_dispatch:
    types: [destroy]

jobs:
  dispatch_and_destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Check message
        id: check_message
        run: echo "::set-output name=Would you like to destroy (yes/no)::${{ github.event.client_payload.message }}"

      - name: Run Destroy Command if message is "yes"
        if: ${{ steps.check_message.outputs.message == 'yes' }}
        run: terraform destroy -auto-approve
      - name: Run if message is "no"
        if: ${{ steps.check_message.outputs.message == 'no' }}
        run: exit 1